name: Around the Corner Productions
favicon: null
layout_spectrum: 0.75447
typography_spectrum: 0.51078
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.675870229722932
  lightness: 0.7370329075492918
  saturation: 0.8373703008983284
  rhythmicContrast: 0.7416789713315666
purpose: []
