name: Panther Sports Talk
favicon: null
layout_spectrum: 0.23927
typography_spectrum: 0.51078
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e6ab1f'
    - '#4e2976'
    - '#816b9c'
    - '#e0e0e0'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
